// src/app/agents/productData.ts
// Product data layer for the Creative Director. Mock catalog; replace with Supabase when ready.
// styleTags: extra match terms beyond title/material/finish (used by CD scorer).
// compatibility_key: cross-slot pairing (e.g. tile_floor ↔ tile_wall).
// metal_match_key: hardware ↔ lighting pairing.

import type { ProductCandidate } from "./projectManagerAgent.types";

type MockProduct = ProductCandidate & { styleTags?: string[] };

const MOCK_CANDIDATES_BY_SLOT: Record<string, MockProduct[]> = {
  // ─── TILE FLOOR ──────────────────────────────────────────────────────────────
  tile_floor: [
    // Parisian heroes
    {
      id: "mock.tf_marble_basketweave",
      vendor: "mock",
      vendor_sku: "tf_marble_basketweave",
      slotId: "tile_floor",
      title: "Marble basketweave floor",
      material: "marble",
      finish: "honed",
      finish_family: "honed stone",
      compatibility_key: "marble_wall_pair",
      tier: "Luxury",
      price: 28,
      currency: "USD",
      styleTags: ["marble basketweave", "tight grout", "crisp alignment", "small to medium scale"],
    },
    {
      id: "mock.tf_marble_herringbone",
      vendor: "mock",
      vendor_sku: "tf_marble_herringbone",
      slotId: "tile_floor",
      title: "Marble herringbone floor",
      material: "marble",
      finish: "polished",
      finish_family: "polished stone",
      compatibility_key: "marble_wall_pair",
      tier: "Luxury",
      price: 32,
      currency: "USD",
      styleTags: ["marble herringbone", "directional rhythm", "polished marble"],
    },
    {
      id: "mock.tf_checkerboard_marble",
      vendor: "mock",
      vendor_sku: "tf_checkerboard_marble",
      slotId: "tile_floor",
      title: "Checkerboard marble floor",
      material: "marble",
      finish: "honed",
      finish_family: "honed stone",
      compatibility_key: "marble_wall_pair",
      tier: "Luxury",
      price: 35,
      currency: "USD",
      styleTags: ["checkerboard marble", "honed marble", "symmetry", "borders"],
    },
    {
      id: "mock.tf_penny_round_marble",
      vendor: "mock",
      vendor_sku: "tf_penny_round_marble",
      slotId: "tile_floor",
      title: "Penny round with dot or floral motifs and border marble floor",
      material: "marble",
      finish: "honed",
      finish_family: "honed stone",
      compatibility_key: "marble_wall_pair",
      tier: "Luxury",
      price: 38,
      currency: "USD",
      styleTags: ["penny round with dot or floral motifs + border", "marble mosaics", "decorative inset rug mosaic", "radial / fan / geometric mosaic (accent)"],
    },
    // Provincial heroes
    {
      id: "mock.tf_terracotta_herringbone",
      vendor: "mock",
      vendor_sku: "tf_terracotta_herringbone",
      slotId: "tile_floor",
      title: "Terracotta herringbone raw antique floor",
      material: "terracotta",
      finish: "raw",
      finish_family: "raw natural",
      compatibility_key: "terracotta_zellige_pair",
      tier: "Elevated",
      price: 18,
      currency: "USD",
      styleTags: ["terracotta herringbone (raw/antique)", "warm grout", "visible joints", "finish/patina > geometry", "earned patina", "reclaimed Belgian terracotta"],
    },
    {
      id: "mock.tf_octagon_dot_stone",
      vendor: "mock",
      vendor_sku: "tf_octagon_dot_stone",
      slotId: "tile_floor",
      title: "Octagon and dot stone tile floor",
      material: "stone",
      finish: "honed",
      finish_family: "honed stone",
      compatibility_key: "terracotta_zellige_pair",
      tier: "Elevated",
      price: 22,
      currency: "USD",
      styleTags: ["octagon + dot stone", "finish/patina > geometry", "grounded materials"],
    },
    {
      id: "mock.tf_limestone_straight",
      vendor: "mock",
      vendor_sku: "tf_limestone_straight",
      slotId: "tile_floor",
      title: "Straight-laid limestone floor",
      material: "limestone",
      finish: "honed",
      finish_family: "honed stone",
      tier: "Elevated",
      price: 20,
      currency: "USD",
      styleTags: ["straight-laid limestone", "bush-hammered limestone", "warm grout", "visible joints"],
    },
    {
      id: "mock.tf_antique_hex",
      vendor: "mock",
      vendor_sku: "tf_antique_hex",
      slotId: "tile_floor",
      title: "Antique hex stone tile floor",
      material: "stone",
      finish: "antique",
      finish_family: "raw natural",
      tier: "Elevated",
      price: 24,
      currency: "USD",
      styleTags: ["antique hex (irregular edges)", "soft checkerboard stone (muted)", "finish/patina > geometry"],
    },
    {
      id: "mock.tf_black_terracotta",
      vendor: "mock",
      vendor_sku: "tf_black_terracotta",
      slotId: "tile_floor",
      title: "Black terracotta square tile floor",
      material: "terracotta",
      finish: "raw",
      finish_family: "raw natural",
      compatibility_key: "terracotta_zellige_pair",
      tier: "Elevated",
      price: 16,
      currency: "USD",
      styleTags: ["terracotta", "warm grout", "visible joints", "dark", "moody"],
    },
    // Mediterranean heroes
    {
      id: "mock.tf_zellige_square_grid",
      vendor: "mock",
      vendor_sku: "tf_zellige_square_grid",
      slotId: "tile_floor",
      title: "Zellige square grid floor",
      material: "zellige",
      finish: "glazed",
      finish_family: "glazed ceramic",
      compatibility_key: "zellige_plaster_pair",
      tier: "Luxury",
      price: 30,
      currency: "USD",
      styleTags: ["zellige square grid", "glaze variation required", "grout as texture", "handmade surfaces"],
    },
    {
      id: "mock.tf_glazed_ceramic_basketweave",
      vendor: "mock",
      vendor_sku: "tf_glazed_ceramic_basketweave",
      slotId: "tile_floor",
      title: "Glazed ceramic basketweave block stack floor",
      material: "ceramic",
      finish: "glazed",
      finish_family: "glazed ceramic",
      compatibility_key: "zellige_plaster_pair",
      tier: "Elevated",
      price: 22,
      currency: "USD",
      styleTags: ["basketweave glazed ceramic (block/stack)", "glaze variation required", "brick / running bond glazed tile"],
    },
    {
      id: "mock.tf_artisanal_mosaic",
      vendor: "mock",
      vendor_sku: "tf_artisanal_mosaic",
      slotId: "tile_floor",
      title: "Small-scale artisanal mosaic tile floor",
      material: "ceramic",
      finish: "glazed",
      finish_family: "glazed ceramic",
      compatibility_key: "zellige_plaster_pair",
      tier: "Luxury",
      price: 40,
      currency: "USD",
      styleTags: ["small-scale artisanal mosaic", "patterned cement (accent zones)", "irregular stone set loosely", "handmade surfaces"],
    },
    // Neutral / rental-safe
    {
      id: "mock.tf_porcelain_matte",
      vendor: "mock",
      vendor_sku: "tf_porcelain_matte",
      slotId: "tile_floor",
      title: "Porcelain matte neutral floor",
      material: "porcelain",
      finish: "matte",
      finish_family: "matte porcelain",
      compatibility_key: "neutral_grout",
      tier: "Value",
      price: 8,
      currency: "USD",
      styleTags: ["porcelain", "neutral", "durable"],
    },
  ],

  // ─── TILE WALL ───────────────────────────────────────────────────────────────
  tile_wall: [
    // Parisian
    {
      id: "mock.tw_subway_refined",
      vendor: "mock",
      vendor_sku: "tw_subway_refined",
      slotId: "tile_wall",
      title: "Subway tile refined white ceramic",
      material: "ceramic",
      finish: "glazed",
      finish_family: "glazed ceramic",
      tier: "Value",
      price: 6,
      currency: "USD",
      styleTags: ["subway tile (refined)", "bordered compositions", "inset panel / framed tile", "composition feels architectural"],
    },
    {
      id: "mock.tw_thassos_subway",
      vendor: "mock",
      vendor_sku: "tw_thassos_subway",
      slotId: "tile_wall",
      title: "Thassos marble subway wall",
      material: "marble",
      finish: "polished",
      finish_family: "polished stone",
      compatibility_key: "marble_wall_pair",
      tier: "Luxury",
      price: 24,
      currency: "USD",
      styleTags: ["marble subway", "subway tile (refined)", "luminous", "thassos", "borders symmetry alignment"],
    },
    {
      id: "mock.tw_inset_panel",
      vendor: "mock",
      vendor_sku: "tw_inset_panel",
      slotId: "tile_wall",
      title: "Inset panel framed tile wall",
      material: "ceramic",
      finish: "glazed",
      finish_family: "glazed ceramic",
      tier: "Elevated",
      price: 14,
      currency: "USD",
      styleTags: ["inset panel / framed tile", "bordered compositions", "composition feels architectural and tailored"],
    },
    // Provincial
    {
      id: "mock.tw_zellige_muted",
      vendor: "mock",
      vendor_sku: "tw_zellige_muted",
      slotId: "tile_wall",
      title: "Zellige weathered white muted grid wall",
      material: "zellige",
      finish: "glazed",
      finish_family: "glazed ceramic",
      compatibility_key: "terracotta_zellige_pair",
      tier: "Elevated",
      price: 18,
      currency: "USD",
      styleTags: ["zellige in muted simple grid", "brick/offset layouts with visible grout", "subway tile (low contrast grout)", "natural texture"],
    },
    // Mediterranean
    {
      id: "mock.tw_zellige_colored_bejmat",
      vendor: "mock",
      vendor_sku: "tw_zellige_colored_bejmat",
      slotId: "tile_wall",
      title: "Zellige colored bejmat wall",
      material: "zellige",
      finish: "glazed",
      finish_family: "glazed ceramic",
      compatibility_key: "zellige_plaster_pair",
      tier: "Elevated",
      price: 22,
      currency: "USD",
      styleTags: ["colored zellige walls", "tadelakt", "variation is mandatory", "grout as texture", "over/dry grout (stone)"],
    },
    {
      id: "mock.tw_tadelakt",
      vendor: "mock",
      vendor_sku: "tw_tadelakt",
      slotId: "tile_wall",
      title: "Tadelakt wall finish",
      material: "tadelakt",
      finish: "smooth",
      finish_family: "plaster",
      tier: "Luxury",
      price: 32,
      currency: "USD",
      styleTags: ["tadelakt", "lime plaster / hand-troweled plaster", "curved plaster forms", "diffused light", "handmade surfaces"],
    },
    // Neutral (all archetypes)
    {
      id: "mock.tw_smooth_plaster",
      vendor: "mock",
      vendor_sku: "tw_smooth_plaster",
      slotId: "tile_wall",
      title: "Smooth plaster wall finish",
      material: "plaster",
      finish: "smooth",
      finish_family: "plaster",
      tier: "Elevated",
      price: 12,
      currency: "USD",
      styleTags: ["plaster walls", "smooth plaster", "hand-applied plaster", "hand-troweled plaster"],
    },
    {
      id: "mock.tw_limewash",
      vendor: "mock",
      vendor_sku: "tw_limewash",
      slotId: "tile_wall",
      title: "Limewash hand-applied wall",
      material: "limewash",
      finish: "raw",
      finish_family: "plaster",
      tier: "Elevated",
      price: 10,
      currency: "USD",
      styleTags: ["plaster walls", "hand-applied plaster", "earned patina", "organic rhythm"],
    },
  ],

  // ─── TILE SHOWER ─────────────────────────────────────────────────────────────
  tile_shower: [
    // Parisian
    {
      id: "mock.ts_marble_subway_large",
      vendor: "mock",
      vendor_sku: "ts_marble_subway_large",
      slotId: "tile_shower",
      title: "Large format honed marble subway shower wall",
      material: "marble",
      finish: "honed",
      finish_family: "honed stone",
      compatibility_key: "marble_wall_pair",
      tier: "Luxury",
      price: 30,
      currency: "USD",
      styleTags: ["large format subway honed marble", "plaster walls", "honed marble"],
    },
    {
      id: "mock.ts_marble_herringbone",
      vendor: "mock",
      vendor_sku: "ts_marble_herringbone",
      slotId: "tile_shower",
      title: "Herringbone honed marble shower wall",
      material: "marble",
      finish: "honed",
      finish_family: "honed stone",
      compatibility_key: "marble_wall_pair",
      tier: "Luxury",
      price: 34,
      currency: "USD",
      styleTags: ["herringbone honed marble", "marble herringbone", "honed marble"],
    },
    // Provincial
    {
      id: "mock.ts_subway_low_contrast",
      vendor: "mock",
      vendor_sku: "ts_subway_low_contrast",
      slotId: "tile_shower",
      title: "Subway tile low contrast grout shower wall",
      material: "ceramic",
      finish: "matte",
      finish_family: "matte ceramic",
      tier: "Value",
      price: 10,
      currency: "USD",
      styleTags: ["subway tile with low contrast grout", "plaster walls", "subway tile (low contrast grout)"],
    },
    // Mediterranean
    {
      id: "mock.ts_zellige_shower",
      vendor: "mock",
      vendor_sku: "ts_zellige_shower",
      slotId: "tile_shower",
      title: "Zellige shower walls",
      material: "zellige",
      finish: "glazed",
      finish_family: "glazed ceramic",
      compatibility_key: "zellige_plaster_pair",
      tier: "Luxury",
      price: 38,
      currency: "USD",
      styleTags: ["zellige walls", "colored zellige walls", "variation is mandatory", "handmade surfaces"],
    },
    {
      id: "mock.ts_penny_tile_shower",
      vendor: "mock",
      vendor_sku: "ts_penny_tile_shower",
      slotId: "tile_shower",
      title: "Penny tile shower floor mosaic",
      material: "marble",
      finish: "honed",
      finish_family: "honed stone",
      tier: "Elevated",
      price: 22,
      currency: "USD",
      styleTags: ["penny tile floor", "small mosaic floor", "marble mosaics"],
    },
    // Neutral
    {
      id: "mock.ts_plaster_shower",
      vendor: "mock",
      vendor_sku: "ts_plaster_shower",
      slotId: "tile_shower",
      title: "Plaster shower walls",
      material: "plaster",
      finish: "smooth",
      finish_family: "plaster",
      tier: "Elevated",
      price: 16,
      currency: "USD",
      styleTags: ["plaster walls", "smooth plaster", "hand-troweled plaster"],
    },
  ],

  // ─── LIGHTING ────────────────────────────────────────────────────────────────
  lighting: [
    // Parisian heroes
    {
      id: "mock.lt_milk_glass_sconce",
      vendor: "mock",
      vendor_sku: "lt_milk_glass_sconce",
      slotId: "lighting",
      title: "Milk glass opaline sconce",
      material: "glass",
      finish: "polished",
      finish_family: "glass",
      metal_match_key: "brass",
      fixtureType: "sconce",
      tier: "Elevated",
      price: 180,
      currency: "USD",
      styleTags: ["milk glass / opaline sconces", "paired wall sconces (symmetry)", "2750–3000K", "symmetry required for hero lighting"],
    },
    {
      id: "mock.lt_fluted_glass_sconce",
      vendor: "mock",
      vendor_sku: "lt_fluted_glass_sconce",
      slotId: "lighting",
      title: "Fluted glass sconce",
      material: "glass",
      finish: "polished",
      finish_family: "glass",
      metal_match_key: "brass",
      fixtureType: "sconce",
      tier: "Elevated",
      price: 220,
      currency: "USD",
      styleTags: ["fluted glass sconces", "paired wall sconces (symmetry)", "shades/globes feel architectural", "2750–3000K"],
    },
    {
      id: "mock.lt_deco_globe_sconce",
      vendor: "mock",
      vendor_sku: "lt_deco_globe_sconce",
      slotId: "lighting",
      title: "Deco-inspired globe paired sconce",
      material: "glass",
      finish: "polished",
      finish_family: "glass",
      metal_match_key: "brass",
      fixtureType: "sconce",
      tier: "Luxury",
      price: 280,
      currency: "USD",
      styleTags: ["deco-inspired globes / stepped forms", "paired wall sconces (symmetry)", "symmetry required for hero lighting"],
    },
    {
      id: "mock.lt_alabaster_sconce",
      vendor: "mock",
      vendor_sku: "lt_alabaster_sconce",
      slotId: "lighting",
      title: "Alabaster sconce",
      material: "alabaster",
      finish: "honed",
      finish_family: "stone",
      metal_match_key: "brass",
      fixtureType: "sconce",
      tier: "Luxury",
      price: 340,
      currency: "USD",
      styleTags: ["alabaster sconces", "picture lights", "slim linear accents", "polished brass", "2750–3000K"],
    },
    // Provincial heroes
    {
      id: "mock.lt_disk_pendant",
      vendor: "mock",
      vendor_sku: "lt_disk_pendant",
      slotId: "lighting",
      title: "Disk pendant",
      material: "metal",
      finish: "aged",
      finish_family: "aged metal",
      metal_match_key: "iron",
      fixtureType: "overhead",
      tier: "Elevated",
      price: 190,
      currency: "USD",
      styleTags: ["disk pendants", "lighting feels useful first", "slight irregularity acceptable", "patinated metals", "aged brass"],
    },
    {
      id: "mock.lt_candle_sconce",
      vendor: "mock",
      vendor_sku: "lt_candle_sconce",
      slotId: "lighting",
      title: "Candle-inspired sconce",
      material: "metal",
      finish: "aged",
      finish_family: "aged metal",
      metal_match_key: "brass",
      fixtureType: "sconce",
      tier: "Elevated",
      price: 140,
      currency: "USD",
      styleTags: ["candle-inspired sconces", "simple lantern forms", "aged brass", "visible mounting/hardware ok", "warm light preferred"],
    },
    {
      id: "mock.lt_torch_wall_light",
      vendor: "mock",
      vendor_sku: "lt_torch_wall_light",
      slotId: "lighting",
      title: "Torch-style wall light",
      material: "iron",
      finish: "blackened",
      finish_family: "blackened metal",
      metal_match_key: "iron",
      fixtureType: "sconce",
      tier: "Elevated",
      price: 165,
      currency: "USD",
      styleTags: ["torch-style wall lights", "blackened or oil-rubbed iron", "visible mounting/hardware ok", "lighting feels useful first"],
    },
    {
      id: "mock.lt_cone_dome_pendant",
      vendor: "mock",
      vendor_sku: "lt_cone_dome_pendant",
      slotId: "lighting",
      title: "Simple cone or dome pendant",
      material: "metal",
      finish: "matte",
      finish_family: "matte metal",
      metal_match_key: "iron",
      fixtureType: "overhead",
      tier: "Value",
      price: 120,
      currency: "USD",
      styleTags: ["simple cone or dome pendants", "ceramic bases (restrained)", "lighting feels useful first"],
    },
    // Mediterranean heroes
    {
      id: "mock.lt_plaster_sconce",
      vendor: "mock",
      vendor_sku: "lt_plaster_sconce",
      slotId: "lighting",
      title: "Plaster sconce",
      material: "plaster",
      finish: "smooth",
      finish_family: "plaster",
      metal_match_key: "brass",
      fixtureType: "sconce",
      tier: "Elevated",
      price: 195,
      currency: "USD",
      styleTags: ["plaster sconces", "diffused light", "light supports texture, not geometry", "asymmetry acceptable", "2400–2700K"],
    },
    {
      id: "mock.lt_ceramic_sconce",
      vendor: "mock",
      vendor_sku: "lt_ceramic_sconce",
      slotId: "lighting",
      title: "Ceramic sconce",
      material: "ceramic",
      finish: "glazed",
      finish_family: "glazed ceramic",
      metal_match_key: "brass",
      fixtureType: "sconce",
      tier: "Elevated",
      price: 175,
      currency: "USD",
      styleTags: ["ceramic sconces", "diffused light", "2400–2700K", "asymmetry acceptable"],
    },
    {
      id: "mock.lt_clay_lantern",
      vendor: "mock",
      vendor_sku: "lt_clay_lantern",
      slotId: "lighting",
      title: "Clay lantern overhead",
      material: "clay",
      finish: "raw",
      finish_family: "raw natural",
      metal_match_key: "brass",
      fixtureType: "overhead",
      tier: "Elevated",
      price: 210,
      currency: "USD",
      styleTags: ["lanterns (clay/alabaster)", "diffused light", "2400–2700K", "handmade look"],
    },
    {
      id: "mock.lt_woven_pendant",
      vendor: "mock",
      vendor_sku: "lt_woven_pendant",
      slotId: "lighting",
      title: "Woven natural-fiber pendant",
      material: "woven",
      finish: "raw",
      finish_family: "natural fiber",
      metal_match_key: "brass",
      fixtureType: "overhead",
      tier: "Elevated",
      price: 155,
      currency: "USD",
      styleTags: ["woven pendants", "hidden/indirect lighting", "diffused light", "2400–2700K"],
    },
    // Neutral / overhead fallback
    {
      id: "mock.lt_linear_overhead_nickel",
      vendor: "mock",
      vendor_sku: "lt_linear_overhead_nickel",
      slotId: "lighting",
      title: "Linear overhead nickel fixture",
      material: "metal",
      finish: "polished",
      finish_family: "polished metal",
      metal_match_key: "nickel",
      fixtureType: "overhead",
      tier: "Value",
      price: 120,
      currency: "USD",
      styleTags: ["slim linear accents", "polished nickel"],
    },
  ],

  // ─── VANITY ──────────────────────────────────────────────────────────────────
  vanity: [
    // Parisian heroes
    {
      id: "mock.va_furniture_fluted",
      vendor: "mock",
      vendor_sku: "va_furniture_fluted",
      slotId: "vanity",
      title: "Furniture-style vanity fluted fronts slim profile elevated",
      material: "wood",
      finish: "painted",
      finish_family: "painted wood",
      compatibility_key: "parisian_vanity",
      tier: "Luxury",
      price: 3200,
      currency: "USD",
      styleTags: ["furniture-style vanity", "fluted fronts", "inset panels", "slim profiles", "elevated off floor", "refined toe-kick", "brass hardware (visible)", "painted wood (soft white/greige/muted)"],
    },
    {
      id: "mock.va_walnut_slim",
      vendor: "mock",
      vendor_sku: "va_walnut_slim",
      slotId: "vanity",
      title: "Slim profile elevated walnut vanity",
      material: "wood",
      finish: "walnut",
      finish_family: "natural wood",
      compatibility_key: "parisian_vanity",
      tier: "Elevated",
      price: 2400,
      currency: "USD",
      styleTags: ["furniture-style vanity", "slim profiles", "elevated off floor", "integrated marble top", "slab backsplash"],
    },
    // Provincial heroes
    {
      id: "mock.va_inset_shaker_painted",
      vendor: "mock",
      vendor_sku: "va_inset_shaker_painted",
      slotId: "vanity",
      title: "Inset shaker doors painted wood vanity chunky proportions",
      material: "wood",
      finish: "painted",
      finish_family: "painted wood",
      compatibility_key: "provincial_vanity",
      tier: "Elevated",
      price: 1800,
      currency: "USD",
      styleTags: ["inset or shaker doors", "chunkier proportions", "painted wood (cream/soft gray/muted blue)", "grounded stance (legs or plinth)", "simple tactile hardware", "built, solid, enduring (worktable energy)"],
    },
    {
      id: "mock.va_tongue_groove_oak",
      vendor: "mock",
      vendor_sku: "va_tongue_groove_oak",
      slotId: "vanity",
      title: "Tongue-and-groove natural oak vanity chunky",
      material: "wood",
      finish: "natural oak",
      finish_family: "natural wood",
      compatibility_key: "provincial_vanity",
      tier: "Elevated",
      price: 2000,
      currency: "USD",
      styleTags: ["tongue-and-groove", "chunkier proportions", "natural wood (oak)", "visible joinery acceptable", "grounded stance (legs or plinth)"],
    },
    // Mediterranean heroes
    {
      id: "mock.va_masonry_plaster",
      vendor: "mock",
      vendor_sku: "va_masonry_plaster",
      slotId: "vanity",
      title: "Masonry plaster base vanity monolithic",
      material: "plaster",
      finish: "smooth",
      finish_family: "plaster",
      compatibility_key: "mediterranean_vanity",
      tier: "Luxury",
      price: 2800,
      currency: "USD",
      styleTags: ["masonry or plaster base", "monolithic concrete/stone forms", "open shelving", "imperfection acceptable", "can feel built-in and architectural"],
    },
    {
      id: "mock.va_tiled_front",
      vendor: "mock",
      vendor_sku: "va_tiled_front",
      slotId: "vanity",
      title: "Tiled vanity front ceramic",
      material: "tile",
      finish: "glazed",
      finish_family: "glazed ceramic",
      compatibility_key: "mediterranean_vanity",
      tier: "Elevated",
      price: 2200,
      currency: "USD",
      styleTags: ["tiled vanity", "vessel sink", "open shelving", "whitewashed wood fronts", "curved raised backsplash"],
    },
  ],

  // ─── COUNTERTOP ──────────────────────────────────────────────────────────────
  countertop: [
    {
      id: "mock.ct_polished_marble_thin",
      vendor: "mock",
      vendor_sku: "ct_polished_marble_thin",
      slotId: "countertop",
      title: "Polished marble thin profile pencil edge",
      material: "marble",
      finish: "polished",
      finish_family: "polished stone",
      compatibility_key: "marble_family",
      tier: "Luxury",
      price: 120,
      currency: "USD",
      styleTags: ["polished marble", "thin profile stone", "thin pencil edge / crisp edge", "refined limestone"],
    },
    {
      id: "mock.ct_honed_marble",
      vendor: "mock",
      vendor_sku: "ct_honed_marble",
      slotId: "countertop",
      title: "Honed marble countertop",
      material: "marble",
      finish: "honed",
      finish_family: "honed stone",
      compatibility_key: "marble_family",
      tier: "Luxury",
      price: 110,
      currency: "USD",
      styleTags: ["honed marble", "polished/honed marble", "integrated marble top", "honed marble top"],
    },
    {
      id: "mock.ct_limestone_thick",
      vendor: "mock",
      vendor_sku: "ct_limestone_thick",
      slotId: "countertop",
      title: "Limestone thick eased softened edge countertop",
      material: "limestone",
      finish: "honed",
      finish_family: "honed stone",
      compatibility_key: "limestone_family",
      tier: "Elevated",
      price: 85,
      currency: "USD",
      styleTags: ["limestone", "thicker profile", "eased edge / softened edge", "honed marble top", "limestone top"],
    },
    {
      id: "mock.ct_travertine_chiseled",
      vendor: "mock",
      vendor_sku: "ct_travertine_chiseled",
      slotId: "countertop",
      title: "Travertine chiseled organic edge countertop",
      material: "travertine",
      finish: "honed",
      finish_family: "honed stone",
      compatibility_key: "limestone_family",
      tier: "Elevated",
      price: 90,
      currency: "USD",
      styleTags: ["travertine", "chiseled edge / organic thickness", "creamy limestone", "honed marble", "bush-hammered stone with patina"],
    },
    {
      id: "mock.ct_limestone_thin",
      vendor: "mock",
      vendor_sku: "ct_limestone_thin",
      slotId: "countertop",
      title: "Refined limestone thin profile countertop",
      material: "limestone",
      finish: "honed",
      finish_family: "honed stone",
      compatibility_key: "limestone_family",
      tier: "Elevated",
      price: 80,
      currency: "USD",
      styleTags: ["refined limestone", "thin profile stone", "thin pencil edge / crisp edge"],
    },
    {
      id: "mock.ct_quartz_honed",
      vendor: "mock",
      vendor_sku: "ct_quartz_honed",
      slotId: "countertop",
      title: "Honed quartz countertop neutral",
      material: "quartz",
      finish: "honed",
      finish_family: "quartz",
      compatibility_key: "quartz_neutral",
      tier: "Value",
      price: 55,
      currency: "USD",
      styleTags: ["quartz", "durable", "neutral", "maintenance-friendly"],
    },
  ],

  // ─── HARDWARE ────────────────────────────────────────────────────────────────
  hardware: [
    {
      id: "mock.hw_polished_brass_fluted",
      vendor: "mock",
      vendor_sku: "hw_polished_brass_fluted",
      slotId: "hardware",
      title: "Polished brass fluted beveled cabinet pull",
      material: "brass",
      finish: "polished",
      finish_family: "polished brass",
      metal_match_key: "brass",
      tier: "Elevated",
      price: 28,
      currency: "USD",
      styleTags: ["polished brass", "fluted or beveled forms", "hardware is visible and intentional"],
    },
    {
      id: "mock.hw_polished_nickel",
      vendor: "mock",
      vendor_sku: "hw_polished_nickel",
      slotId: "hardware",
      title: "Polished nickel beveled cabinet pull",
      material: "metal",
      finish: "polished",
      finish_family: "polished nickel",
      metal_match_key: "nickel",
      tier: "Elevated",
      price: 24,
      currency: "USD",
      styleTags: ["polished nickel", "fluted or beveled forms"],
    },
    {
      id: "mock.hw_aged_brass",
      vendor: "mock",
      vendor_sku: "hw_aged_brass",
      slotId: "hardware",
      title: "Aged brass simple tactile cabinet pull",
      material: "brass",
      finish: "aged",
      finish_family: "aged brass",
      metal_match_key: "brass",
      tier: "Elevated",
      price: 22,
      currency: "USD",
      styleTags: ["aged brass", "simple tactile pulls", "patinated metals"],
    },
    {
      id: "mock.hw_iron_blackened",
      vendor: "mock",
      vendor_sku: "hw_iron_blackened",
      slotId: "hardware",
      title: "Blackened oil-rubbed iron cabinet pull",
      material: "iron",
      finish: "blackened",
      finish_family: "blackened iron",
      metal_match_key: "iron",
      tier: "Elevated",
      price: 20,
      currency: "USD",
      styleTags: ["iron hardware", "raw/blackened metal", "controlled blackened metal", "simple tactile pulls"],
    },
    {
      id: "mock.hw_hammered_brass",
      vendor: "mock",
      vendor_sku: "hw_hammered_brass",
      slotId: "hardware",
      title: "Hammered brass cabinet pull",
      material: "brass",
      finish: "hammered",
      finish_family: "hammered brass",
      metal_match_key: "brass",
      tier: "Elevated",
      price: 26,
      currency: "USD",
      styleTags: ["hammered brass", "handmade look", "unlacquered brass"],
    },
    {
      id: "mock.hw_matte_iron",
      vendor: "mock",
      vendor_sku: "hw_matte_iron",
      slotId: "hardware",
      title: "Matte iron cabinet pull",
      material: "iron",
      finish: "matte",
      finish_family: "matte iron",
      metal_match_key: "iron",
      tier: "Value",
      price: 16,
      currency: "USD",
      styleTags: ["matte iron", "handmade look"],
    },
    {
      id: "mock.hw_painted_ceramic",
      vendor: "mock",
      vendor_sku: "hw_painted_ceramic",
      slotId: "hardware",
      title: "Painted ceramic handmade cabinet pull",
      material: "ceramic",
      finish: "painted",
      finish_family: "ceramic",
      metal_match_key: "brass",
      tier: "Elevated",
      price: 30,
      currency: "USD",
      styleTags: ["painted ceramic pulls", "handmade look"],
    },
  ],

  // ─── ARCHITECTURE ─────────────────────────────────────────────────────────────
  architecture: [
    {
      id: "mock.ar_wall_molding_paneling",
      vendor: "mock",
      vendor_sku: "ar_wall_molding_paneling",
      slotId: "architecture",
      title: "Wall molding and paneling Haussmann proportions",
      material: "wood",
      finish: "painted",
      finish_family: "painted wood",
      tier: "Luxury",
      price: 0,
      currency: "USD",
      styleTags: ["wall molding / paneling", "Haussmann proportions", "strong vertical lines", "symmetry", "beveled mirror"],
    },
    {
      id: "mock.ar_exposed_beams",
      vendor: "mock",
      vendor_sku: "ar_exposed_beams",
      slotId: "architecture",
      title: "Exposed beams visible joinery arched openings",
      material: "wood",
      finish: "natural oak",
      finish_family: "natural wood",
      tier: "Elevated",
      price: 0,
      currency: "USD",
      styleTags: ["exposed beams", "visible joinery", "arched openings", "wood shutters"],
    },
    {
      id: "mock.ar_rounded_arcs",
      vendor: "mock",
      vendor_sku: "ar_rounded_arcs",
      slotId: "architecture",
      title: "Rounded corners organic arcs soft-cube geometry",
      material: "plaster",
      finish: "smooth",
      finish_family: "plaster",
      tier: "Elevated",
      price: 0,
      currency: "USD",
      styleTags: ["rounded corners", "organic arcs", "soft stucco vaults", "painted shutters (blue/olive)", "iron grilles"],
    },
  ],

  // ─── CEILING ─────────────────────────────────────────────────────────────────
  ceiling: [
    {
      id: "mock.ce_coffered",
      vendor: "mock",
      vendor_sku: "ce_coffered",
      slotId: "ceiling",
      title: "Coffered paneled ceiling with crown molding",
      material: "wood",
      finish: "painted",
      finish_family: "painted wood",
      tier: "Luxury",
      price: 0,
      currency: "USD",
      styleTags: ["coffered ceilings", "crown molding", "paneled ceilings"],
    },
    {
      id: "mock.ce_exposed_beams",
      vendor: "mock",
      vendor_sku: "ce_exposed_beams",
      slotId: "ceiling",
      title: "Exposed beams oak whitewashed plaster curves",
      material: "wood",
      finish: "whitewashed",
      finish_family: "natural wood",
      tier: "Elevated",
      price: 0,
      currency: "USD",
      styleTags: ["exposed beams (oak/whitewashed)", "gentle plaster curves"],
    },
    {
      id: "mock.ce_white_plaster_vault",
      vendor: "mock",
      vendor_sku: "ce_white_plaster_vault",
      slotId: "ceiling",
      title: "White plaster stucco vault wood slats",
      material: "plaster",
      finish: "smooth",
      finish_family: "plaster",
      tier: "Elevated",
      price: 0,
      currency: "USD",
      styleTags: ["white plaster", "wood slats", "woven reed", "soft stucco vaults"],
    },
  ],
};

const SLOT_IDS = Object.keys(MOCK_CANDIDATES_BY_SLOT);

/**
 * Get product candidates for a slot. Today: returns mock data.
 * Later: query Supabase master_products by category/slot, material, finish, etc.
 */
export function getCandidatesForSlot(
  slotKey: string,
  _filters?: { archetype?: string; material?: string; metalMatchKey?: string }
): MockProduct[] {
  const [baseSlotId, roomId] = slotKey.includes("|") ? slotKey.split("|") : [slotKey, undefined];
  const candidates = MOCK_CANDIDATES_BY_SLOT[baseSlotId] ?? [];
  return candidates.map((c) => ({
    ...c,
    slotId: baseSlotId,
    ...(roomId ? { roomId } : {}),
  }));
}

/** Get all slot keys that have mock data. */
export function getMockSlotIds(): string[] {
  return [...SLOT_IDS];
}
